repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.13.1
    hooks:
      - id: stylua-github
        name: StyLua (Github)
        description: An opinionated Lua code formatter. Downloads Github release
        entry: stylua
        language: python
        types:
          - lua
